NAME:"Americana"
ICON:"images/icons/american.png"

TEAM : BLACK
BOARD : 8
FLYING_KINGS : FALSE
PEONS_CAPTURE_BACKWARDS : FALSE
PEONS_MOVEMENT : WHITE_BOTTOM_TO_TOP

APPLY_LAW_OF_QUANTITY : FALSE
APPLY_LAW_OF_QUALITY : FALSE

DOUBLE_CORNER_SIDE : TRUE

[1;12] : BLACK_PEON
[21;32] : WHITE_PEON