NAME:"Internacional"
ICON:"images/icons/international.png"

TEAM : WHITE
BOARD : 10
FLYING_KINGS : TRUE
PEONS_CAPTURE_BACKWARDS : TRUE
PEONS_MOVEMENT : WHITE_BOTTOM_TO_TOP

APPLY_LAW_OF_QUANTITY : TRUE
APPLY_LAW_OF_QUALITY : FALSE

DOUBLE_CORNER_SIDE : TRUE

[1;20] : BLACK_PEON
[31;50] : WHITE_PEON