NAME:"Portuguesa"
ICON:"images/icons/portuguese.png"

TEAM : WHITE
BOARD : 8
FLYING_KINGS : TRUE
PEONS_CAPTURE_BACKWARDS : FALSE
PEONS_MOVEMENT : WHITE_BOTTOM_TO_TOP

APPLY_LAW_OF_QUANTITY : TRUE
APPLY_LAW_OF_QUALITY : TRUE

DOUBLE_CORNER_SIDE : FALSE

[1;12] : BLACK_PEON
[21;32] : WHITE_PEON