#ifndef DEF_STATIC_TEXT_HEADER
#define DEF_STATIC_TEXT_HEADER

#define PT_MENUS 1

#define LOG_MESSAGE_CHALLENGE_COMPLETED "Challenge Completed"
#define LOG_MESSAGE_BLACK_TEAM_WON      "Black Team Won"
#define LOG_MESSAGE_WHITE_TEAM_WON      "White Team Won"

#if PT_MENUS == 1
#define UI_MESSAGE_CHALLENGE_COMPLETED  "Desafio Concluido"
#define UI_MESSAGE_BLACK_TEAM_WON       "Negras Venceram"
#define UI_MESSAGE_WHITE_TEAM_WON       "Brancas Venceram"

#define UI_START_BUTTON_TEXT "JOGAR"
#define UI_EDITOR_BUTTON_TEXT "EDITOR"
#define UI_QUIT_BUTTON_TEXT "SAIR"
#define UI_BACK_BUTTON_TEXT "VOLTAR"

#else
#define UI_MESSAGE_CHALLENGE_COMPLETED  LOG_MESSAGE_CHALLENGE_COMPLETED
#define UI_MESSAGE_BLACK_TEAM_WON       LOG_MESSAGE_BLACK_TEAM_WON
#define UI_MESSAGE_WHITE_TEAM_WON       LOG_MESSAGE_WHITE_TEAM_WON

#define UI_START_BUTTON_TEXT "START"
#define UI_EDITOR_BUTTON_TEXT "EDITOR"
#define UI_QUIT_BUTTON_TEXT "QUIT"
#define UI_BACK_BUTTON_TEXT "BACK"

#endif

#endif